# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\dashboard.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dashboard(object):
    def setupUi(self, Dashboard):
        Dashboard.setObjectName("Dashboard")
        Dashboard.resize(943, 646)
        self.centralwidget = QtWidgets.QWidget(Dashboard)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color:rgb(33, 33, 33)")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_7 = QtWidgets.QFrame(self.frame)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_welcome = QtWidgets.QLabel(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_welcome.sizePolicy().hasHeightForWidth())
        self.label_welcome.setSizePolicy(sizePolicy)
        self.label_welcome.setStyleSheet("color:white;\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.label_welcome.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_welcome.setObjectName("label_welcome")
        self.horizontalLayout_3.addWidget(self.label_welcome)
        self.btn_logout = QtWidgets.QPushButton(self.frame_7)
        self.btn_logout.setStyleSheet("color:black;\n"
"background-color:rgb(85, 170, 255);\n"
"padding:6px 20px;\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"border-radius:5px;\n"
"")
        self.btn_logout.setObjectName("btn_logout")
        self.horizontalLayout_3.addWidget(self.btn_logout)
        self.btn_settings = QtWidgets.QPushButton(self.frame_7)
        self.btn_settings.setStyleSheet("background:transparent")
        self.btn_settings.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\ui\\../resources/images/settings-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_settings.setIcon(icon)
        self.btn_settings.setIconSize(QtCore.QSize(25, 25))
        self.btn_settings.setObjectName("btn_settings")
        self.horizontalLayout_3.addWidget(self.btn_settings)
        self.verticalLayout_3.addWidget(self.frame_7)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setStyleSheet("background-color:rgb(42, 42, 42)")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        spacerItem1 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_7.addItem(spacerItem1)
        self.frame_6 = QtWidgets.QFrame(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setStyleSheet("\n"
"border-radius:20px;\n"
"")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_8 = QtWidgets.QFrame(self.frame_6)
        self.frame_8.setStyleSheet("background:transparent")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.frame_8)
        self.label_4.setStyleSheet("color: rgb(207, 207, 207);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.line = QtWidgets.QFrame(self.frame_8)
        self.line.setStyleSheet("background-color:rgb(156, 156, 156);\n"
"border:1px inset black;")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_4.addWidget(self.line)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.frame_9 = QtWidgets.QFrame(self.frame_8)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_14 = QtWidgets.QFrame(self.frame_9)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_9 = QtWidgets.QLabel(self.frame_14)
        self.label_9.setStyleSheet("color:white;\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.label_9.setObjectName("label_9")
        self.verticalLayout_12.addWidget(self.label_9)
        self.comboBox_pacing_mode = QtWidgets.QComboBox(self.frame_14)
        self.comboBox_pacing_mode.setMinimumSize(QtCore.QSize(121, 35))
        self.comboBox_pacing_mode.setStyleSheet("QComboBox {\n"
"    border: 2px solid  #55aaff;\n"
"    border-radius: 10px;\n"
"    padding: 1px 18px 1px 3px;\n"
"    min-width: 6em;\n"
"    color:white;\n"
"    font: 10pt \"MS Shell Dlg 2\";\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"  border: 2px inset gray;\n"
"  background: rgb(33, 33, 33);\n"
"  selection-background-color: black;\n"
"selection-color:#55aaff;\n"
"color:white;\n"
"border-radius:none;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px;\n"
"    border-left-width: 1px;\n"
"    border-left-color:  #55aaff;\n"
"    border-left-style: solid; /* just a single line */\n"
"    border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"border-left: 7px solid none;\n"
"                               border-right: 7px solid none; border-top: 5px solid #55aaff; width: 0px; height: 0px;\n"
"}\n"
"\n"
"QComboBox::down-arrow:on { /* shift the arrow when popup is open */\n"
"    top: 1px;\n"
"    left: 1px;\n"
"}\n"
"QComboBox::item {\n"
"    border-top: 4;\n"
"    border-left: 4;\n"
"    border-bottom: 4;\n"
"    border-right: 4;\n"
"    background-color: #C87020;\n"
"    color: rgb(200, 112, 32);\n"
"}")
        self.comboBox_pacing_mode.setObjectName("comboBox_pacing_mode")
        self.comboBox_pacing_mode.addItem("")
        self.comboBox_pacing_mode.addItem("")
        self.comboBox_pacing_mode.addItem("")
        self.comboBox_pacing_mode.addItem("")
        self.verticalLayout_12.addWidget(self.comboBox_pacing_mode)
        self.verticalLayout_11.addWidget(self.frame_14)
        self.verticalLayout_4.addWidget(self.frame_9)
        self.frame_15 = QtWidgets.QFrame(self.frame_8)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_15)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_10 = QtWidgets.QFrame(self.frame_15)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.frame_10)
        self.label_5.setStyleSheet("color:white;\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5)
        self.spinBox_url = QtWidgets.QSpinBox(self.frame_10)
        self.spinBox_url.setMinimumSize(QtCore.QSize(0, 35))
        self.spinBox_url.setStyleSheet("QSpinBox{\n"
"border:2px solid #55aaff;\n"
"border-radius:10px;\n"
"color:white;\n"
"    font: 10pt \"MS Shell Dlg 2\";\n"
"}\n"
"QSpinBox::up-arrow { border-left:10px solid none;\n"
"                               border-right:  10px solid none; border-bottom: 7px solid #55aaff; width: 0px; height: 0px; }\n"
"\n"
"QSpinBox::down-arrow { border-left: 10px solid none;\n"
"                               border-right: 10px solid none; border-top: 7px solid #55aaff; width: 0px; height: 0px; }")
        self.spinBox_url.setMinimum(90)
        self.spinBox_url.setMaximum(180)
        self.spinBox_url.setObjectName("spinBox_url")
        self.verticalLayout_6.addWidget(self.spinBox_url)
        self.gridLayout_2.addWidget(self.frame_10, 0, 1, 1, 1)
        self.frame_16 = QtWidgets.QFrame(self.frame_15)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_16)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_10 = QtWidgets.QLabel(self.frame_16)
        self.label_10.setStyleSheet("color:white;\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.label_10.setObjectName("label_10")
        self.verticalLayout_13.addWidget(self.label_10)
        self.lineEdit_va = QtWidgets.QLineEdit(self.frame_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_va.sizePolicy().hasHeightForWidth())
        self.lineEdit_va.setSizePolicy(sizePolicy)
        self.lineEdit_va.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_va.setStyleSheet("border:2px solid #55aaff;\n"
"border-radius:10px;\n"
"color:white;\n"
"    font: 10pt \"MS Shell Dlg 2\";")
        self.lineEdit_va.setObjectName("lineEdit_va")
        self.verticalLayout_13.addWidget(self.lineEdit_va)
        self.gridLayout_2.addWidget(self.frame_16, 2, 0, 1, 1)
        self.frame_12 = QtWidgets.QFrame(self.frame_15)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_7 = QtWidgets.QLabel(self.frame_12)
        self.label_7.setStyleSheet("color:white;\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.label_7.setObjectName("label_7")
        self.verticalLayout_9.addWidget(self.label_7)
        self.lineEdit_av = QtWidgets.QLineEdit(self.frame_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_av.sizePolicy().hasHeightForWidth())
        self.lineEdit_av.setSizePolicy(sizePolicy)
        self.lineEdit_av.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_av.setStyleSheet("border:2px solid #55aaff;\n"
"border-radius:10px;\n"
"color:white;\n"
"    font: 10pt \"MS Shell Dlg 2\";")
        self.lineEdit_av.setObjectName("lineEdit_av")
        self.verticalLayout_9.addWidget(self.lineEdit_av)
        self.gridLayout_2.addWidget(self.frame_12, 1, 0, 1, 1)
        self.frame_17 = QtWidgets.QFrame(self.frame_15)
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_17)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_11 = QtWidgets.QLabel(self.frame_17)
        self.label_11.setStyleSheet("color:white;\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.label_11.setObjectName("label_11")
        self.verticalLayout_14.addWidget(self.label_11)
        self.spinBox_vpw = QtWidgets.QSpinBox(self.frame_17)
        self.spinBox_vpw.setMinimumSize(QtCore.QSize(0, 35))
        self.spinBox_vpw.setStyleSheet("QSpinBox{\n"
"border:2px solid #55aaff;\n"
"border-radius:10px;\n"
"color:white;\n"
"    font: 10pt \"MS Shell Dlg 2\";\n"
"}\n"
"QSpinBox::up-arrow { border-left:10px solid none;\n"
"                               border-right:  10px solid none; border-bottom: 7px solid #55aaff; width: 0px; height: 0px; }\n"
"\n"
"QSpinBox::down-arrow { border-left: 10px solid none;\n"
"                               border-right: 10px solid none; border-top: 7px solid #55aaff; width: 0px; height: 0px; }")
        self.spinBox_vpw.setMinimum(1)
        self.spinBox_vpw.setMaximum(100)
        self.spinBox_vpw.setObjectName("spinBox_vpw")
        self.verticalLayout_14.addWidget(self.spinBox_vpw)
        self.gridLayout_2.addWidget(self.frame_17, 2, 1, 1, 1)
        self.frame_13 = QtWidgets.QFrame(self.frame_15)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_8 = QtWidgets.QLabel(self.frame_13)
        self.label_8.setStyleSheet("color:white;\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.label_8.setObjectName("label_8")
        self.verticalLayout_10.addWidget(self.label_8)
        self.spinBox_apw = QtWidgets.QSpinBox(self.frame_13)
        self.spinBox_apw.setMinimumSize(QtCore.QSize(0, 35))
        self.spinBox_apw.setStyleSheet("QSpinBox{\n"
"border:2px solid #55aaff;\n"
"border-radius:10px;\n"
"color:white;\n"
"    font: 10pt \"MS Shell Dlg 2\";\n"
"}\n"
"QSpinBox::up-arrow { border-left:10px solid none;\n"
"                               border-right:  10px solid none; border-bottom: 7px solid #55aaff; width: 0px; height: 0px; }\n"
"\n"
"QSpinBox::down-arrow { border-left: 10px solid none;\n"
"                               border-right: 10px solid none; border-top: 7px solid #55aaff; width: 0px; height: 0px; }")
        self.spinBox_apw.setMinimum(1)
        self.spinBox_apw.setMaximum(100)
        self.spinBox_apw.setObjectName("spinBox_apw")
        self.verticalLayout_10.addWidget(self.spinBox_apw)
        self.gridLayout_2.addWidget(self.frame_13, 1, 1, 1, 1)
        self.frame_11 = QtWidgets.QFrame(self.frame_15)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_6 = QtWidgets.QLabel(self.frame_11)
        self.label_6.setStyleSheet("color:white;\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_8.addWidget(self.label_6)
        self.spinBox_lrl = QtWidgets.QSpinBox(self.frame_11)
        self.spinBox_lrl.setMinimumSize(QtCore.QSize(0, 35))
        self.spinBox_lrl.setStyleSheet("QSpinBox{\n"
"border:2px solid #55aaff;\n"
"border-radius:10px;\n"
"color:white;\n"
"    font: 10pt \"MS Shell Dlg 2\";\n"
"}\n"
"QSpinBox::up-arrow { border-left:10px solid none;\n"
"                               border-right:  10px solid none; border-bottom: 7px solid #55aaff; width: 0px; height: 0px; }\n"
"\n"
"QSpinBox::down-arrow { border-left: 10px solid none;\n"
"                               border-right: 10px solid none; border-top: 7px solid #55aaff; width: 0px; height: 0px; }")
        self.spinBox_lrl.setMinimum(30)
        self.spinBox_lrl.setMaximum(90)
        self.spinBox_lrl.setObjectName("spinBox_lrl")
        self.verticalLayout_8.addWidget(self.spinBox_lrl)
        self.gridLayout_2.addWidget(self.frame_11, 0, 0, 1, 1)
        self.frame_18 = QtWidgets.QFrame(self.frame_15)
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_18)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_12 = QtWidgets.QLabel(self.frame_18)
        self.label_12.setStyleSheet("color:white;\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.label_12.setObjectName("label_12")
        self.verticalLayout_15.addWidget(self.label_12)
        self.lineEdit_vrp = QtWidgets.QLineEdit(self.frame_18)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_vrp.sizePolicy().hasHeightForWidth())
        self.lineEdit_vrp.setSizePolicy(sizePolicy)
        self.lineEdit_vrp.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_vrp.setStyleSheet("border:2px solid #55aaff;\n"
"border-radius:10px;\n"
"color:white;\n"
"    font: 10pt \"MS Shell Dlg 2\";")
        self.lineEdit_vrp.setObjectName("lineEdit_vrp")
        self.verticalLayout_15.addWidget(self.lineEdit_vrp)
        self.gridLayout_2.addWidget(self.frame_18, 3, 0, 1, 1)
        self.frame_19 = QtWidgets.QFrame(self.frame_15)
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_19)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_13 = QtWidgets.QLabel(self.frame_19)
        self.label_13.setStyleSheet("color:white;\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.label_13.setObjectName("label_13")
        self.verticalLayout_16.addWidget(self.label_13)
        self.lineEdit_arp = QtWidgets.QLineEdit(self.frame_19)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_arp.sizePolicy().hasHeightForWidth())
        self.lineEdit_arp.setSizePolicy(sizePolicy)
        self.lineEdit_arp.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_arp.setStyleSheet("border:2px solid #55aaff;\n"
"border-radius:10px;\n"
"color:white;\n"
"    font: 10pt \"MS Shell Dlg 2\";")
        self.lineEdit_arp.setObjectName("lineEdit_arp")
        self.verticalLayout_16.addWidget(self.lineEdit_arp)
        self.gridLayout_2.addWidget(self.frame_19, 3, 1, 1, 1)
        self.verticalLayout_4.addWidget(self.frame_15)
        self.verticalLayout_5.addWidget(self.frame_8)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem3)
        self.verticalLayout_7.addWidget(self.frame_6)
        spacerItem4 = QtWidgets.QSpacerItem(20, 3, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_7.addItem(spacerItem4)
        self.horizontalLayout.addWidget(self.frame_5)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.verticalLayout.addWidget(self.frame_2)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setStyleSheet("background-color:rgb(156, 156, 156);\n"
"border:1px inset black;")
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setStyleSheet("background-color:rgb(42, 42, 42)")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem6 = QtWidgets.QSpacerItem(800, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_device_status = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_device_status.setObjectName("horizontalLayout_device_status")
        self.label = QtWidgets.QLabel(self.frame_4)
        self.label.setStyleSheet("color: rgb(207, 207, 207);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.horizontalLayout_device_status.addWidget(self.label)
        self.horizontalLayout_2.addWidget(self.frame_4)
        self.verticalLayout.addWidget(self.frame_3)
        Dashboard.setCentralWidget(self.centralwidget)

        self.retranslateUi(Dashboard)
        QtCore.QMetaObject.connectSlotsByName(Dashboard)

    def retranslateUi(self, Dashboard):
        _translate = QtCore.QCoreApplication.translate
        Dashboard.setWindowTitle(_translate("Dashboard", "Pacemaker: Device Controller Monitor"))
        self.label_welcome.setText(_translate("Dashboard", "Welcome, "))
        self.btn_logout.setText(_translate("Dashboard", "Log Out"))
        self.label_4.setText(_translate("Dashboard", "Pacemaker Parameters"))
        self.label_9.setText(_translate("Dashboard", "Pacing Mode"))
        self.comboBox_pacing_mode.setItemText(0, _translate("Dashboard", "VOO"))
        self.comboBox_pacing_mode.setItemText(1, _translate("Dashboard", "AOO"))
        self.comboBox_pacing_mode.setItemText(2, _translate("Dashboard", "AAI"))
        self.comboBox_pacing_mode.setItemText(3, _translate("Dashboard", "VVI"))
        self.label_5.setText(_translate("Dashboard", "Upper Rate Limit (URL) [bpm]"))
        self.label_10.setText(_translate("Dashboard", "Ventricular Amplitude (V)"))
        self.label_7.setText(_translate("Dashboard", "Atrial Amplitude (V)"))
        self.label_11.setText(_translate("Dashboard", "Ventricular Pulse Width (ms)"))
        self.label_8.setText(_translate("Dashboard", "Atrial Pulses Width (ms)"))
        self.label_6.setText(_translate("Dashboard", "Lower Rate Limit (LRL) [bpm]"))
        self.label_12.setText(_translate("Dashboard", "Ventricular Refractory Period (VRP)"))
        self.label_13.setText(_translate("Dashboard", "Atrial Refractory Period (ARP)"))
        self.label.setText(_translate("Dashboard", "Device Status"))
